### ISSUE TITLE
PCとバトルしたいな…

### ISSUE THREAD

**Issue by akaishikiso** [CODEDUEL2022/CODEDUEL#13]
CPU戦を追加したいな…

機械学習はしんどいけど、まぁ、合った方が嬉しい

CPU戦はwebsocketを使用しないから、マルチ戦より楽かも
ここで対戦機能を実装して、そこからマルチに持っていきたいな

**Comment by YutaK1026** [comment]
現状の実装で起こりうるバグ

- [ ] CPUの行動ターン中にリロードすると止まる
　　-> controlTurn周りの実装を考え直す。フロントのみで処理でも良いかもしれない。
- [ ] 適宜あれば追加記述
