### ISSUE TITLE
Roomがfullでも入室が出来る

### ISSUE THREAD

**Issue by YutaK1026** [CODEDUEL2022/CODEDUEL#38]

**Comment by Riku-0801** [comment]
メインページ？でこのルームで遊ぶボタンを押すとルームにいる人数が返されて、
＞二人未満のとき、スタートボタンが押せるようになる
＞二人以上のとき、スタートボタンが押せない（ルームの上限人数を超えていますとか出す）
ってすれば良さそうかな
